### ISSUE TITLE
error installing under macOS ($ npm i openzim/libzim)

### ISSUE THREAD

**Issue by eranhr** [openzim/node-libzim#53] opened 2020-11-08 16:23 UTC
When I run `npm i openzim/libzim` I get this error:

```
> [Sat Nov 07 12:01:28] [libzim] [1]$   npm i openzim/libzim
> npm ERR! premature close
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/**********/.npm/_logs/2020-11-08T12_02_50_054Z-debug.log
```

**Comment by kelson42** [comment] 2020-11-21 11:32
Please share the full debug log

**Comment by eranhr** [comment] 2020-11-22 05:57
macOs catalina 10.15.7 (19H2)

adding log file and then terminal output:

**log file:**

> 0 info it worked if it ends with ok
> 1 verbose cli [
> 1 verbose cli   '/usr/local/Cellar/node/13.13.0/bin/node',
> 1 verbose cli   '/usr/local/bin/npm',
> 1 verbose cli   'i',
> 1 verbose cli   'openzim/libzim'
> 1 verbose cli ]
> 2 info using npm@6.14.4
> 3 info using node@v13.13.0
> 4 verbose npm-session 731be0e5ed2691b9
> 5 silly install loadCurrentTree
> 6 silly install readLocalPackageData
> 7 silly fetchPackageMetaData error for github:openzim/libzim premature close
> 8 timing stage:rollbackFailedOptional Completed in 1ms
> 9 timing stage:runTopLevelLifecycles Completed in 13055ms
> 10 verbose stack Error: premature close
> 10 verbose stack     at PassThrough.onclose (/usr/local/lib/node_modules/npm/node_modules/end-of-stream/index.js:47:67)
> 10 verbose stack     at PassThrough.emit (events.js:327:22)
> 10 verbose stack     at emitCloseNT (internal/streams/destroy.js:80:8)
> 10 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:83:21)
> 11 verbose cwd /Users/**********/temp/libzim
> 12 verbose Darwin 19.6.0
> 13 verbose argv "/usr/local/Cellar/node/13.13.0/bin/node" "/usr/local/bin/npm" "i" "openzim/libzim"
> 14 verbose node v13.13.0
> 15 verbose npm  v6.14.4
> 16 error premature close
> 17 verbose exit [ 1, true ]



**Terminal output:**

> [libzim] [12]$   npm i libzim
> 
> libzim@1.0.0 install /Users/**********/temp/node_modules/libzim
> node-pre-gyp install --fallback-to-build
> 
> node-pre-gyp info it worked if it ends with ok
> node-pre-gyp verb cli [
> node-pre-gyp verb cli   '/usr/local/Cellar/node/13.13.0/bin/node',
> node-pre-gyp verb cli   '/Users/**********/temp/node_modules/libzim/node_modules/.bin/node-pre-gyp',
> node-pre-gyp verb cli   'install',
> node-pre-gyp verb cli   '--fallback-to-build'
> node-pre-gyp verb cli ]
> node-pre-gyp info using node-pre-gyp@0.6.29
> node-pre-gyp info using node@13.13.0 | darwin | x64
> node-pre-gyp verb command install []
> node-pre-gyp info check checked for "/Users/**********/temp/node_modules/libzim/lib/binding/node-v79-darwin-x64/zim.node" (not found)
> node-pre-gyp http GET https://github.com/cscott/node-libzim/releases/download/1.0.0/zim-v1.0.0-node-v79-darwin-x64.tar.gz
> node-pre-gyp http 404 https://github.com/cscott/node-libzim/releases/download/1.0.0/zim-v1.0.0-node-v79-darwin-x64.tar.gz
> node-pre-gyp ERR! Tried to download: https://github.com/cscott/node-libzim/releases/download/1.0.0/zim-v1.0.0-node-v79-darwin-x64.tar.gz 
> node-pre-gyp ERR! Pre-built binaries not found for libzim@1.0.0 and node@13.13.0 (node-v79 ABI) (falling back to source compile with node-gyp) 
> node-pre-gyp http Pre-built binary not available for your system, looked for https://github.com/cscott/node-libzim/releases/download/1.0.0/zim-v1.0.0-node-v79-darwin-x64.tar.gz 
> node-pre-gyp verb command build [ 'rebuild' ]
> node-pre-gyp ERR! Tried to download: https://github.com/cscott/node-libzim/releases/download/1.0.0/zim-v1.0.0-node-v79-darwin-x64.tar.gz 
> node-pre-gyp ERR! Pre-built binaries not found for libzim@1.0.0 and node@13.13.0 (node-v79 ABI) (falling back to source compile with node-gyp) 
> node-pre-gyp http Connection closed while downloading tarball file 
> node-pre-gyp verb command build [ 'rebuild' ]
>   ACTION deps_libzim_gyp_action_before_build_target_configure_libzim Release/obj/gen/Makefile
>   ACTION deps_libzim_gyp_action_before_build_target_configure_libzim Release/obj/gen/Makefile
> Changing to /Users/**********/temp/node_modules/libzim/build/Release/obj/gen/
> /Users/**********/temp/node_modules/libzim/deps/openzim/zimlib/autogen.sh
> Changing to /Users/**********/temp/node_modules/libzim/build/Release/obj/gen/
> /Users/**********/temp/node_modules/libzim/deps/openzim/zimlib/autogen.sh
> /Users/**********/temp/node_modules/libzim/deps/cdconfigure.js:36
>     if (err) { throw err; }
>                ^
> 
> Error: Command failed: /Users/**********/temp/node_modules/libzim/deps/openzim/zimlib/autogen.sh
> /Users/**********/temp/node_modules/libzim/deps/openzim/zimlib/autogen.sh: line 6: glibtoolize: command not found
> /Users/**********/temp/node_modules/libzim/deps/openzim/zimlib/autogen.sh: line 12: aclocal: command not found
> /Users/**********/temp/node_modules/libzim/deps/openzim/zimlib/autogen.sh: line 13: autoheader: command not found
> /Users/**********/temp/node_modules/libzim/deps/openzim/zimlib/autogen.sh: line 14: autoconf: command not found
> /Users/**********/temp/node_modules/libzim/deps/openzim/zimlib/autogen.sh: line 15: automake: command not found
> 
>     at ChildProcess.exithandler (child_process.js:303:12)
>     at ChildProcess.emit (events.js:315:20)
>     at maybeClose (internal/child_process.js:1026:16)
>     at Socket.<anonymous> (internal/child_process.js:441:11)
>     at Socket.emit (events.js:315:20)
>     at Pipe.<anonymous> (net.js:674:12) {
>   killed: false,
>   code: 127,
>   signal: null,
>   cmd: '/Users/**********/temp/node_modules/libzim/deps/openzim/zimlib/autogen.sh'
> }
> /Users/**********/temp/node_modules/libzim/deps/cdconfigure.js:36
>     if (err) { throw err; }
>                ^
> 
> Error: Command failed: /Users/**********/temp/node_modules/libzim/deps/openzim/zimlib/autogen.sh
> /Users/**********/temp/node_modules/libzim/deps/openzim/zimlib/autogen.sh: line 6: glibtoolize: command not found
> /Users/**********/temp/node_modules/libzim/deps/openzim/zimlib/autogen.sh: line 12: aclocal: command not found
> /Users/**********/temp/node_modules/libzim/deps/openzim/zimlib/autogen.sh: line 13: autoheader: command not found
> /Users/**********/temp/node_modules/libzim/deps/openzim/zimlib/autogen.sh: line 14: autoconf: command not found
> /Users/**********/temp/node_modules/libzim/deps/openzim/zimlib/autogen.sh: line 15: automake: command not found
> 
>     at ChildProcess.exithandler (child_process.js:303:12)
>     at ChildProcess.emit (events.js:315:20)
>     at maybeClose (internal/child_process.js:1026:16)
>     at Socket.<anonymous> (internal/child_process.js:441:11)
>     at Socket.emit (events.js:315:20)
>     at Pipe.<anonymous> (net.js:674:12) {
>   killed: false,
>   code: 127,
>   signal: null,
>   cmd: '/Users/**********/temp/node_modules/libzim/deps/openzim/zimlib/autogen.sh'
> }
> make: *** [Release/obj/gen/Makefile] Error 1
> make: *** [Release/obj/gen/Makefile] Error 1
> gypgyp ERR!  build error 
> ERR! build error 
> gyp gyp ERR! ERR! stack Error: `make` failed with exit code: 2
> stackgyp  Error: `make` failed with exit code: 2
> ERR!gyp  stackERR!     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:194:23)
>  gyp stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:194:23)
> gypERR!  stack     at ChildProcess.emit (events.js:315:20)
> ERR! gypstack      at ChildProcess.emit (events.js:315:20)
> ERR! stackgyp      at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
> ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
> gyp ERR!gyp ERR! System  Darwin 19.6.0
> Systemgyp Darwin 19.6.0
>  ERR! command "/usr/local/Cellar/node/13.13.0/bin/node" "/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/**********/temp/node_modules/libzim/lib/binding/node-v79-darwin-x64/zim.node" "--module_name=zim" "--module_path=/Users/**********/temp/node_modules/libzim/lib/binding/node-v79-darwin-x64"
> gypgyp  ERR!ERR!  commandcwd "/usr/local/Cellar/node/13.13.0/bin/node" "/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/**********/temp/node_modules/libzim/lib/binding/node-v79-darwin-x64/zim.node" "--module_name=zim" "--module_path=/Users/**********/temp/node_modules/libzim/lib/binding/node-v79-darwin-x64"
> gyp ERR! cwd /Users/**********/temp/node_modules/libzim
> gyp ERR! node -v v13.13.0
> gyp ERR! node-gyp -v v7.1.2
> 
> gyp ERR! not ok 
> gyp ERR! node -v v13.13.0
> gyp ERR! node-gyp -v v7.1.2
> gyp ERR! not ok 
> node-pre-gyp ERR! build error 
> node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/13.13.0/bin/node /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/**********/temp/node_modules/libzim/lib/binding/node-v79-darwin-x64/zim.node --module_name=zim --module_path=/Users/**********/temp/node_modules/libzim/lib/binding/node-v79-darwin-x64' (1)
> node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/**********/temp/node_modules/libzim/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
> node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
> node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1026:16)
> node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
> node-pre-gyp ERR! System Darwin 19.6.0
> node-pre-gyp ERR! command "/usr/local/Cellar/node/13.13.0/bin/node" "/Users/**********/temp/node_modules/libzim/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
> node-pre-gyp ERR! cwd /Users/**********/temp/node_modules/libzim
> node-pre-gyp ERR! node -v v13.13.0
> node-pre-gyp ERR! node-pre-gyp -v v0.6.29
> node-pre-gyp ERR! not ok 
> Failed to execute '/usr/local/Cellar/node/13.13.0/bin/node /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/**********/temp/node_modules/libzim/lib/binding/node-v79-darwin-x64/zim.node --module_name=zim --module_path=/Users/**********/temp/node_modules/libzim/lib/binding/node-v79-darwin-x64' (1)
> npm WARN temp@1.0.0 No description
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! libzim@1.0.0 install: `node-pre-gyp install --fallback-to-build`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the libzim@1.0.0 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/**********/.npm/_logs/2020-11-06T10_16_29_817Z-debug.log

**Comment by eranhr** [comment] 2020-11-22 05:59
I'm pointing you again to this line of code in the package installment:

> node-pre-gyp http GET https://github.com/cscott/node-libzim/releases/download/1.0.0/zim-v1.0.0-node-v79-darwin-x64.tar.gz


which is an invalid URL... and this is the response to this line of code:
> node-pre-gyp http 404 https://github.com/cscott/node-libzim/releases/download/1.0.0/zim-v1.0.0-node-v79-darwin-x64.tar.gz
> node-pre-gyp ERR! Tried to download: https://github.com/cscott/node-libzim/releases/download/1.0.0/zim-v1.0.0-node-v79-darwin-x64.tar.gz

**Comment by kelson42** [comment] 2020-11-22 08:30
For the thousand time, please stop providing a log for package libzim. I want the log for the package openzim/libzim.

**Comment by eranhr** [comment] 2020-11-22 13:42
be more polite please.

**terminal output:**

> [Sun Nov 22 15:37:39] [libzim] 13$ npm i openzim/libzim
> npm ERR! premature close
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/*******/.npm/_logs/2020-11-22T13_38_06_629Z-debug.log

log file:
> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'i', 'openzim/libzim' ]
> 2 info using npm@6.12.1
> 3 info using node@v12.13.1
> 4 verbose npm-session 5a8c00c65f9c65dc
> 5 silly install loadCurrentTree
> 6 silly install readLocalPackageData
> 7 silly fetchPackageMetaData error for github:openzim/libzim premature close
> 8 timing stage:rollbackFailedOptional Completed in 0ms
> 9 timing stage:runTopLevelLifecycles Completed in 24678ms
> 10 verbose stack Error: premature close
> 10 verbose stack     at PassThrough.onclose (/usr/local/lib/node_modules/npm/node_modules/end-of-stream/index.js:47:67)
> 10 verbose stack     at PassThrough.emit (events.js:215:7)
> 10 verbose stack     at emitCloseNT (internal/streams/destroy.js:69:8)
> 10 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:79:21)
> 11 verbose cwd /Users/********/LocalFiles/temp/libzim
> 12 verbose Darwin 19.4.0
> 13 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "openzim/libzim"
> 14 verbose node v12.13.1
> 15 verbose npm  v6.12.1
> 16 error premature close
> 17 verbose exit [ 1, true ]

**Comment by kelson42** [comment] 2020-11-22 15:11
There is nothing in the log you have provided which can help me to understand what goes wrong here.

**Comment by eranhr** [comment] 2020-12-02 11:21
Tried it in 3 different macos. never mind. will find some other ways to read zim files.

**Comment by kelson42** [comment] 2020-12-08 06:55
Please leave this ticket open. I want to see further comments and investigations first.

**Comment by kelson42** [comment] 2020-12-22 16:43
@eranhr Why do you keep closing this ticket although I ask to keep it open?

**Comment by kelson42** [comment] 2021-01-03 20:30
Quite sure meanwhile this has been caused by an outdated version of npm.

**Closed by kelson42** 2021-01-03 20:30 UTC
Labels: question
